const TYPE_OF_HOME = "TYPE_OF_HOME";
const CONDITION = "CONDITION";
const BEDROOMS = "BEDROOMS";
const PRICE_RANGE = "PRICE_RANGE";
const BATHROOMS = "BATHROOMS";
const PUBLICATION_DATE = "PUBLICATION_DATE";
const EQUIPAMENT = "EQUIPAMENT";
const MORE_FILTERS = "MORE_FILTERS";

export { TYPE_OF_HOME, CONDITION, BEDROOMS, PRICE_RANGE, BATHROOMS, PUBLICATION_DATE, EQUIPAMENT, MORE_FILTERS };
